### ISSUE TITLE
When string is in hindi then it convert that string into ????

### ISSUE THREAD

**Issue by pawanyd14** [BriquzStudio/php-emoji#5]
when we encode the string and if sting message in Hindi then it encodes the message into ???? and when we decode then message then it leaves the message ???? not decode the message into the original message. but emoji is working fine.

**Comment by gzstokiyama** [comment]
1. make sure your file and code is using utf-8 ,not other format
2.we will not maintain this repo anymore,It is highly recommended to utf8mb4 encoding
